version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres  # Use a mesma senha do seu .env
      POSTGRES_DB: monitoramento_viveiro
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres  # Nome do serviço do PostgreSQL
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    working_dir: /app

volumes:
  pg_data: